updated for upload
git-svn-id: http://kmuto.jp/svn/im-switch/tags/im-switch-1.9@62 ee42ece4-0af0-0310-bd0c-e7793d78c489

diff --git a/im-switch b/im-switch
--- a/im-switch
+++ b/im-switch
@@ -28,7 +28,7 @@ LNG=${LNG%.*}
 [ -z "$LNG" ] && LNG="all_ALL" || true
 
 USERID=$(id -u)
-VER=0.3+debian1.5
+VER=0.3+debian1.10
 
 VERBOSE=0
 
@@ -167,7 +167,7 @@ list() {
 	echo "The system wide default is pointed by \"${ALTER_XINPUT}all_ALL\" ."
 	/usr/sbin/update-alternatives --display xinput-all_ALL | sed -e "s%$XINPUT_PATH/%%"
     else
-	echo "No system wide default \"${ALTER_XINPUT}${LNG} ot ${ALTER_XINPUT}all_ALL\" is defined."
+	echo "No system wide default \"${ALTER_XINPUT}${LNG} or ${ALTER_XINPUT}all_ALL\" is defined."
     fi
     vecho "======================================================="
     vecho "The system wide default input methods are available for the locales:"
@@ -198,8 +198,9 @@ list() {
 auto() {
     if [ "$USERID" -eq 0 ]; then
         if [ ! -r "${ALTER_XINPUT}${LNG}" ]; then
-	    echo "No system wide default input method is defined for $LNG." >&2
-	    exit 1
+	    echo "No system wide default defined just for locale ${LNG} ."
+	    echo "Use \"all_ALL\" quasi-locale and set IM."
+            LNG="all_ALL"
         fi
 	PREVIOUS=$(current_system_im)
 	/usr/sbin/update-alternatives --auto xinput-$LNG
@@ -220,23 +221,23 @@ setalt() {
         vecho "You are root user."
         # sanity check
         if [ ! -r "$XINPUT_PATH/$1" ] ; then
-            echo "Error: no system wide configuration link for \"$1\" local exists." >&2
+            echo "Error: no system wide configuration file \"$1\" exists." >&2
 	    echo "Error: No action taken." >&2
             exit 1
         fi
 	if [ ! -r "${ALTER_XINPUT}${LNG}" ]; then
-            echo "Error: no system wide alternatives for \"$1\" local exists." >&2
-	    echo "Error: No action taken." >&2
-            exit 1
+	    echo "No system wide default defined just for locale $LNG ."
+	    echo "Use \"all_ALL\" quasi-locale and set IM."
+            LNG="all_ALL"
 	fi
 	PREVIOUS=$(current_system_im)
-	/usr/sbin/update-alternatives --set xinput-$LNG $XINPUT_PATH/$1
+	/usr/sbin/update-alternatives --set xinput-$LNG $XINPUT_PATH/${1}
         DEFAULT=$(current_system_im)
         vecho "Changed system wide default from $PREVIOUS to $DEFAULT."
     else
         # sanity check
-        if [ ! -r "$XINPUT_PATH/$1" -a ! -r "$DOTXINPUT_PATH/$1" ] ; then
-            echo "Error: no configuration link for \"$1\" local exists." >&2
+        if [ ! -r "$XINPUT_PATH/${1}" -a ! -r "$DOTXINPUT_PATH/${1}" ] ; then
+            echo "Error: no configuration file \"${1}\" exists." >&2
 	    echo "Error: No action taken." >&2
             exit 1
         fi
@@ -250,10 +251,10 @@ setalt() {
             mv ${DOTXINPUT_PATH}/${LNG} ${DOTXINPUT_PATH}/${LNG}.backup
             vecho "Backed up user configuration pointing to $PREVIOUS."
 	fi
-        if [ -r "$DOTXINPUT_PATH/$1" ] ; then
-            ln -s $DOTXINPUT_PATH/$1 ${DOTXINPUT_PATH}/$LNG
+        if [ -r "$DOTXINPUT_PATH/${1}" ] ; then
+            ln -s $DOTXINPUT_PATH/${1} ${DOTXINPUT_PATH}/$LNG
         else
-            ln -s $XINPUT_PATH/$1 ${DOTXINPUT_PATH}/$LNG
+            ln -s $XINPUT_PATH/${1} ${DOTXINPUT_PATH}/$LNG
         fi
         DEFAULT=$(current_user_im)
         vecho "Set user configuration pointing to $DEFAULT."
@@ -267,9 +268,9 @@ cfgalt() {
     if [ "$USERID" -eq 0 ]; then
         vecho "You are root user."
 	if [ ! -r "${ALTER_XINPUT}${LNG}" ]; then
-	    echo "No system wide default defined for locale $LNG ."
-	    echo "No action taken."
-            exit 0
+	    echo "No system wide default defined just for locale $LNG ."
+	    echo "Use \"all_ALL\" quasi-locale and set IM."
+            LNG="all_ALL"
 	fi
 	PREVIOUS=$(current_system_im)
 	/usr/sbin/update-alternatives --config xinput-$LNG
@@ -370,11 +371,11 @@ ORGAT="$@"
 while getopts "vfz:als:ch" OPTION; do
     case $OPTION in
         v) VERBOSE=1;;
-        z) vlang; LNG="$OPTARG";;
+        z) vlang; LNG="$OPTARG"; LNG=${LNG%@*}; LNG=${LNG%.*};;
         a) vlang; auto; exit 0;;
         l) vlang; list; exit 0;;
         s) vlang; setalt "$OPTARG"; exit 0;;
-        c) vlang; cfgalt ; exit 0;;
+        c) vlang; cfgalt; exit 0;;
         h) vlang; help; exit 0;;
 	?) errcmd; exit 1;;
     esac
