fix confusion over LNG and $1
git-svn-id: http://kmuto.jp/svn/im-switch/trunk@59 ee42ece4-0af0-0310-bd0c-e7793d78c489

diff --git a/im-switch b/im-switch
--- a/im-switch
+++ b/im-switch
@@ -28,7 +28,7 @@ LNG=${LNG%.*}
 [ -z "$LNG" ] && LNG="all_ALL" || true
 
 USERID=$(id -u)
-VER=0.3+debian1.5
+VER=0.3+debian1.10
 
 VERBOSE=0
 
@@ -199,7 +199,7 @@ auto() {
     if [ "$USERID" -eq 0 ]; then
         if [ ! -r "${ALTER_XINPUT}${LNG}" ]; then
 	    echo "No system wide default defined just for locale ${LNG} ."
-	    echo "Use \"-z all_ALL\" quasi-locale and set IM."
+	    echo "Use \"all_ALL\" quasi-locale and set IM."
             LNG="all_ALL"
         fi
 	PREVIOUS=$(current_system_im)
@@ -220,10 +220,10 @@ setalt() {
     if [ "$USERID" -eq 0 ]; then
         vecho "You are root user."
         # sanity check
-        if [ ! -r "$XINPUT_PATH/${LNG}" ] ; then
-	    echo "No system wide default defined just for locale ${LNG} ."
-	    echo "Use \"-z all_ALL\" quasi-locale and set IM."
-            LNG="all_ALL"
+        if [ ! -r "$XINPUT_PATH/$1" ] ; then
+            echo "Error: no system wide configuration file \"$1\" exists." >&2
+	    echo "Error: No action taken." >&2
+            exit 1
         fi
 	if [ ! -r "${ALTER_XINPUT}${LNG}" ]; then
             echo "Error: no system wide alternatives for \"${LNG}\" local exists." >&2
@@ -231,13 +231,13 @@ setalt() {
             exit 1
 	fi
 	PREVIOUS=$(current_system_im)
-	/usr/sbin/update-alternatives --set xinput-$LNG $XINPUT_PATH/${LNG}
+	/usr/sbin/update-alternatives --set xinput-$LNG $XINPUT_PATH/${1}
         DEFAULT=$(current_system_im)
         vecho "Changed system wide default from $PREVIOUS to $DEFAULT."
     else
         # sanity check
-        if [ ! -r "$XINPUT_PATH/${LNG}" -a ! -r "$DOTXINPUT_PATH/${LNG}" ] ; then
-            echo "Error: no configuration link for \"${LNG}\" local exists." >&2
+        if [ ! -r "$XINPUT_PATH/${1}" -a ! -r "$DOTXINPUT_PATH/${1}" ] ; then
+            echo "Error: no configuration file \"${1}\" exists." >&2
 	    echo "Error: No action taken." >&2
             exit 1
         fi
@@ -251,10 +251,10 @@ setalt() {
             mv ${DOTXINPUT_PATH}/${LNG} ${DOTXINPUT_PATH}/${LNG}.backup
             vecho "Backed up user configuration pointing to $PREVIOUS."
 	fi
-        if [ -r "$DOTXINPUT_PATH/${LNG}" ] ; then
-            ln -s $DOTXINPUT_PATH/${LNG} ${DOTXINPUT_PATH}/$LNG
+        if [ -r "$DOTXINPUT_PATH/${1}" ] ; then
+            ln -s $DOTXINPUT_PATH/${1} ${DOTXINPUT_PATH}/$LNG
         else
-            ln -s $XINPUT_PATH/${LNG} ${DOTXINPUT_PATH}/$LNG
+            ln -s $XINPUT_PATH/${1} ${DOTXINPUT_PATH}/$LNG
         fi
         DEFAULT=$(current_user_im)
         vecho "Set user configuration pointing to $DEFAULT."
@@ -269,7 +269,7 @@ cfgalt() {
         vecho "You are root user."
 	if [ ! -r "${ALTER_XINPUT}${LNG}" ]; then
 	    echo "No system wide default defined just for locale $LNG ."
-	    echo "Use \"-z all_ALL\" quasi-locale and set IM."
+	    echo "Use \"all_ALL\" quasi-locale and set IM."
             LNG="all_ALL"
 	fi
 	PREVIOUS=$(current_system_im)
@@ -374,7 +374,7 @@ while getopts "vfz:als:ch" OPTION; do
         z) vlang; LNG="$OPTARG"; LNG=${LNG%@*}; LNG=${LNG%.*};;
         a) vlang; auto; exit 0;;
         l) vlang; list; exit 0;;
-        s) vlang; setalt; exit 0;;
+        s) vlang; setalt "$OPTARG"; exit 0;;
         c) vlang; cfgalt; exit 0;;
         h) vlang; help; exit 0;;
 	?) errcmd; exit 1;;
